### ISSUE TITLE
What version of vicuna-7b

### ISSUE THREAD

**Issue by raphael-sch** [zjunlp/TRICE#1]
What version of vicuna-7b is it exactly that you provide the lora weights for? In the adapter config it only says "/data/qiaoshuofei/PLMs/vicuna-7b", but it is not clear if this is v1.1 v1.3 etc

**Comment by GoooDte** [comment]
Hello, we use the v1.1.

**Comment by raphael-sch** [comment]
thanks a lot for the fast answer!

**Comment by raphael-sch** [comment]
and is the provided set of lora weights only for math or trained on the mixed data?

**Comment by GoooDte** [comment]
The provided lora weights was trained on the mixed data.
