### ISSUE TITLE
Experimental Setup in HotpotQA

### ISSUE THREAD

**Issue by obara128** [zjunlp/TRICE#3]
Hi,

I came across your blog post (https://www.zjukg.org/project/TRICE/) and noticed that you conducted experiments using the HotpotQA dataset. I have a question regarding the experimental setup.

In the results table, it mentions "Unseen Tool". Does this mean that a different search engine was used compared to the WikiSearch used for datasets like WebQuestion and NaturalQuestion? If so, could you please specify which search engine was used?

Thank you!

Ryoma Obara

**Comment by GoooDte** [comment]
Hello, here we use a Wikipedia retriever as an unseen tool.

**Comment by obara128** [comment]
Thank you for your response.

Is the "Wikipedia retriever" different from the "WikiSearch" used to tackle WebQuestion and NaturalQuestion? If they are the same, does it mean that Vicuna (TRICE-MIX) used in HotpotQA experiments was not trained with the WikiSearch tool?

**Comment by GoooDte** [comment]
We apologize for the unclear expression. Both `WikiSearch` and `Retriever` are fundamentally based on Wikipedia documents but are different tools. `WikiSearch` directly returns the 2-4 most similar documents that match the keywords, while in `Retriever`, to highlight the retrieval aspect, we perform segmentation (512 tokens) on the retrieved documents and select the top 3-5 segments with the highest similarity as results.

During training, Vicuna (TRICE-MIX) incorporates `WikiSearch`. During testing, we enable Vicuna (TRICE-MIX) to utilize `Retriever` by directly providing instructions such as "Please answer the following question, and you can use a Retriever for help." This allows Vicuna (TRICE-MIX) to leverage the `Retriever` during the testing phase.
