### ISSUE TITLE
I feel that the paper is really pretty good. May I know which conference I am currently submitting to?

### ISSUE THREAD

**Issue by LeiyanGithub** [zjunlp/TRICE#4]

**Comment by GoooDte** [comment]
Tanks for  your attention to our paper, this paper is now under review of ARR.

**Comment by LeiyanGithub** [comment]
Is it because the EMNLP application was not accepted?

**Comment by GoooDte** [comment]
Yes 😭

**Comment by LeiyanGithub** [comment]
So sad, but we think this is a pretty good job. Give me some insights! What aspects do the reviewers consider to be inadequate? Is it because the initial version experiments were not complete enough, not a more complete version now?

**Comment by LeiyanGithub** [comment]
Do you plan to submit to ACL？

**Comment by GoooDte** [comment]
We will decide based on the subsequent reviews' comments.

**Comment by LeiyanGithub** [comment]
I am a little curious why you chose Lora instead of fully fine-tuning？

**Comment by GoooDte** [comment]
We primarily consider the computational resources available and the stability of training.

**Comment by LeiyanGithub** [comment]
Hello, may I ask how to extract answers from the model's response in zero-shot situations, like vicuna?

For example: 
{"id": "SVAMP11", "instruction": "Given a math problem, please solve it", "input": "Winter is almost here and most animals are migrating to warmer countries. 27 bird families flew away for the winter from near a mountain. If there were 41 bird families living near the mountain initially How many bird families were left near the mountain?", "answer": "14.0", "response": "There were 41 bird families living near the mountain initially."}

<img width="802" alt="image" src="https://github.com/zjunlp/TRICE/assets/45895439/996a72a2-37bb-4dbd-8bd6-9823a51612e9">

**Comment by GoooDte** [comment]
We directly extract the last number in the last sentence of the response.
