### ISSUE TITLE
train_on_inputs flag

### ISSUE THREAD

**Issue by lisaalaz** [zjunlp/TRICE#7]
Hi! I noticed that there is a parameter for masking the inputs when computing the loss (for stage 1). By default in the code it is false. Is this the desired setup for training on the math task, and if so could you elaborate why? Thank you

**Comment by GoooDte** [comment]
Hello, sorry for the late reply. Given that this repository has been around for a while, we recall that this parameter was discovered during our experiments to train Llama1. Setting "train_on_inputs" to true worked better for the vanilla Llama1, aiding in instruction following, but overall, the performance was still quite poor. For models like Alpaca and Vicuna, this parameter had little effect, so we did not revert it to false for those models.
